metadata.format.version = "1.1"

[versions]

# Shaded
adventure = "4.26.1"
adventurePlatform = "4.4.1"

jedis = "7.2.1"
bstats = "3.1.0"

# Provided
gson = "2.8.8"
guava = "29.0-jre"
snakeyaml = "1.23"
jetbrainsAnnotations = "26.0.2"

protocollib = "5.3.0"
authlib = "1.5.25"
luckperms = "5.3"
serverlistplus = "3.5.0"

paper = "1.21.11-R0.1-SNAPSHOT"
bungee = "1.21-R0.1-SNAPSHOT"
sponge = "14.0.0"
velocity = "3.4.0"

junitVer = "5.14.2"


[libraries]

adventureApi = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventureTextMinimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventureTextSerializerGson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure" }
adventureTextSerializerLegacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
adventurePlatformBungee = { group = "net.kyori", name = "adventure-platform-bungeecord", version.ref = "adventurePlatform" }

jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrainsAnnotations" }

jedis = {group = "redis.clients", name = "jedis", version.ref = "jedis"}
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
bstatsBukkit = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }
bstatsBungee = { group = "org.bstats", name = "bstats-bungeecord", version.ref = "bstats" }
bstatsSponge = { group = "org.bstats", name = "bstats-sponge", version.ref = "bstats" }
bstatsVelocity = { group = "org.bstats", name = "bstats-velocity", version.ref = "bstats" }

authlib = { group = "com.mojang", name = "authlib", version.ref = "authlib" }
protocollib = { group = "com.comphenix.protocol", name = "ProtocolLib", version.ref = "protocollib" }
luckperms = { group = "net.luckperms", name = "api", version.ref = "luckperms" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeyaml" }
serverlistplus = { group = "net.minecrell", name = "ServerListPlus", version.ref = "serverlistplus" }

paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
bungee = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungee" }
sponge = { group = "org.spongepowered", name = "spongeapi", version.ref = "sponge" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }

jupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitVer" }
jupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitVer" }


[bundles]

adventureBungee = ["adventureApi", "adventureTextMinimessage", "adventureTextSerializerGson", "adventureTextSerializerLegacy", "adventurePlatformBungee"]
junit = ["jupiterApi", "jupiterEngine"]
