# MaintenanceBungee Plugin by KennyTV
# Version ${project.version}

# Enables maintenance-mode.
enable-maintenance-mode: false

# The message shown in the multiplayer server list motd.
# If you put in multiple entries, one of them will be chosen randomly on every ping.
pingmessages:
  - "&cMaintenance mode!%NEWLINE%&6We will be back soon!"
 #- "Another entry"

# If set to true, the message below will be shown at the top right corner of the server in the serverlist,
# where the playercount would normally be displayed.
# If set to false, the normal playercount will be shown.
# Alternatively you can use '%ONLINE%' and '%MAX% if you want to include the playercount in a custom message (e.g. '&cMaintenance &7%ONLINE%&8/&7%MAX%').
enable-playercountmessage: true
playercountmessage: "&4Maintenance"

# Is shown when you move your mouse above the text at the top right corner of the server in the serverlist,
# where the playercount would normally be displayed.
playercounthovermessage: "&cCurrently under%NEWLINE%&cmaintenance"

# Is shown when a player tries to join while maintenance is enabled and they don't have the permission to bypass it.
kickmessage: "&cThe server is currently under maintenance!%NEWLINE%Try again later!"

# If using the timer command: In what intervalls before enabling/disabling maintenance there will be a broadcast.
timer-broadcast-for-seconds: [1200, 900, 600, 300, 120, 60, 30, 20, 10, 5, 4, 3, 2, 1]

# If set to true, players with the maintenance.joinnotification permission will receive a message,
# that a player tried to join the server while maintenance is enabled.
send-join-notification: false

# If set to true, the server icon will be changed to maintenance-icon.png in the Bungee main/base-folder.
custom-maintenance-icon: false

# Only enable MySQL if you really know what you are doing.
mysql:
  use-mysql: false
  host: host
  port: 3306
  database: database
  username: username
  password: password
  # A new table with this name will be created on first startup when 'use-mysql' is set to true.
  table: maintenance_settings
  # Requests to the database will only be made at least x seconds after the last request,
  # so there won't be a request on every single ping on a server with many players.
  # Set this to 0 to make a database request on every single ping.
  update-interval: 15